optimal_binary_search_tree: optimal_binary_search_tree.o
	cc -o optimal_binary_search_tree optimal_binary_search_tree.o

optimal_binary_search_tree.o: optimal_binary_search_tree.c
	cc -c -g optimal_binary_search_tree.c

.PHONY: clean
clean:
	rm -f *.o *~ optimal_binary_search_tree
